# Anh Tu Duong Nguyen (anguyea, 115931)
#
# Anh-Nhat Nguyen (anhnnguy, 2034311)

In [1]:
%load_ext autoreload
%autoreload 2

import torch
from a03_functions import SimpleLSTM
from a03_helper import DEVICE

Seed set to 0


## Task 3: Recurrent Neural Networks

In [2]:
# Test constructor
model = SimpleLSTM(50, 10, 32, 2, 0.1).to(DEVICE)
print(model)

# Should give:
# SimpleLSTM(
#   (embedding): Embedding(50, 10)
#   (lstm): LSTM(10, 32, num_layers=2, batch_first=True, dropout=0.1)
#   (fc): Linear(in_features=32, out_features=1, bias=True)
#   (sigmoid): Sigmoid()
# )

SimpleLSTM(
  (embedding): Embedding(50, 10)
  (lstm): LSTM(10, 32, num_layers=2, batch_first=True, dropout=0.1)
  (fc): Linear(in_features=32, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


In [3]:
# Test forward pass (with a batch of 3 examples)
model = SimpleLSTM(50, 10, 32, 2).to(DEVICE)
dummy_data = torch.arange(30, dtype=torch.int, device=DEVICE).reshape(3, 10)

# Test with fixed model parameters
for key in model.state_dict():
    model.state_dict()[key][:] = 0.1
probs, states = model(dummy_data)
print(probs)
print(states)


# tensor([[0.9643],
#         [0.9643],
#         [0.9643]], device='cuda:0 or cpu', grad_fn=<SigmoidBackward0>)
# tensor([[0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985],
#         [0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985],
#         [0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
#          0.9985, 0.9985, 0.9985, 0.9985, 0.9985]], device='cuda:0 or cpu',
#        grad_fn=<SliceBackward0>)

tensor([[0.9643],
        [0.9643],
        [0.9643]], grad_fn=<SigmoidBackward0>)
tensor([[0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985],
        [0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985],
        [0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985, 0.9985,
         0.9985, 0.9985, 0.9985, 0.9985, 0.9985]], grad_fn=<SelectBackward0>)


In [4]:
# Test with random model parameters
for key in model.state_dict():
    A = model.state_dict()[key]
    A[:] = torch.randn(*A.shape)
probs, states = model(dummy_data)
print(probs)
print(states)
# You should now see different outputs for each of the three examples. Run this multiple
# times; you should see output probabilities in the entire range from [0-1] (i.e., not
# just extremes)

tensor([[0.0424],
        [0.1184],
        [0.2578]], grad_fn=<SigmoidBackward0>)
tensor([[-7.2160e-02,  4.8750e-01, -1.3729e-01,  1.9670e-04,  6.3799e-03,
          2.7479e-02,  9.2322e-02,  3.1899e-04, -4.7886e-03,  1.3670e-02,
         -2.3255e-01,  4.3611e-01,  8.0213e-01,  3.4799e-01,  3.0493e-01,
         -3.5897e-01,  5.3742e-01, -2.0512e-01,  1.9608e-01,  1.4856e-01,
          2.3125e-01,  3.3853e-01, -2.1202e-01,  5.4770e-01,  3.3011e-03,
         -9.3333e-02,  1.8082e-01, -7.9287e-01,  3.6466e-01, -4.6068e-03,
          9.8456e-01,  2.3454e-02],
        [-7.3328e-01,  8.7993e-01,  7.5755e-01,  4.5045e-05,  8.7221e-06,
          6.8065e-01,  7.5435e-01, -1.5880e-02, -2.5996e-02,  6.6947e-01,
         -5.4409e-01,  3.2204e-02,  1.1201e-01, -3.0658e-01,  2.0717e-01,
          4.2481e-02,  1.5784e-01, -1.0838e-03,  1.1128e-01, -1.0671e-04,
          2.0989e-01, -2.3000e-02, -7.5923e-01,  4.9522e-03,  3.7898e-04,
         -8.9311e-01,  1.7698e-03, -4.3762e-01, -1.3623e-01, -3.632