In [1]:
import torch
import numpy as np

%load_ext autoreload
%autoreload 2
from a02_functions import ClimbCNN


# Task 1: Climbing with a CNN

Initialize `model` using the right hyperparameters for task 1a). Then inspect your
model's parameters using `model.state_dict()`. (Note that when using layer
implementations from `torch.nn`, parameters are initialized randomly as discussed in
the lecture.)

In [2]:
model = ClimbCNN(in_channels=1, out_channels=1, kernel_size=2)
print(model.state_dict())

OrderedDict({'conv.weight': tensor([[[0.1672, 0.4991]]]), 'conv.bias': tensor([-0.4830])})


You can access the model parameters via `<model>.<param-name>`. Set all parameters to
the values required to solve task a).

In [3]:
with torch.no_grad():  # needed so that you can assign values to the model parameters
    # TODO: your code here
    model.conv.weight[:] = torch.tensor([[[-1.0, 1.0]]])
    model.conv.bias[:] = torch.tensor([0.0])

Simple test case that can be verified by hand.

In [4]:
x = torch.Tensor([0.0, 5.0, 11.0, 7.0, 15.0, 3.0]).view(1, -1)
with torch.no_grad():
    y = model(x)
print(y)  # should give: tensor([19.])

tensor([[19.]])


Example from the lecture.

In [5]:
climb_data = (
    torch.from_numpy(np.genfromtxt("climb_filtered.csv")).to(torch.float).view(1, -1)
)
with torch.no_grad():
    y = model(torch.Tensor(climb_data).view(1, -1))

print(y)  # should give: tensor([503.4000])

tensor([[503.4000]])


Now create a new `model2` that computes that total ascent (first output) and total descent (second output) simultaneously. Do this using the same model implementation as above, but change only hyperparameters and parameters.

In [6]:
# TODO: your code here
model2 = ClimbCNN(in_channels=1, out_channels=2, kernel_size=2)
with torch.no_grad():  # needed so that you can assign values to the model parameters
    # TODO: your code here
    model2.conv.weight[0] = torch.tensor([[[-1.0, 1.0]]]) # channel 0: ascent
    model2.conv.weight[1] = torch.tensor([[[1.0, -1.0]]]) # channel 1: descent
    model2.conv.bias[:] = torch.tensor([0.0])  # one bias per channel

In [7]:
x = torch.Tensor([0.0, 5.0, 11.0, 7.0, 15.0, 3.0]).view(1, -1)
with torch.no_grad():
    y = model2(x)
print(y)  # should give: [19., 16.]

tensor([[19., 16.]])


In [8]:
with torch.no_grad():
    y = model2(torch.Tensor(climb_data).view(1, -1))

print(y)  # should give: tensor([503.4000, 513.6000])

tensor([[503.4000, 513.6000]])
